// Generated by hand to mirror Rcpp attributes output.

#include <Rcpp.h>

using namespace Rcpp;

// bayesian_mcmc_cpp
Rcpp::List bayesian_mcmc_cpp(const NumericMatrix& vM, int nIter, int burnin, int thin, int seed, int adaptEvery, double targetAccept, bool verbose, int printEvery, bool doMAP, bool zeroIsPadding, double alphaMaxOpt, bool useMAPinit, Nullable<NumericVector> steps_, Nullable<NumericVector> lb_, Nullable<NumericVector> ub_, Nullable<NumericVector> par0_);
RcppExport SEXP _BayesRegulationInference__bayesian_mcmc_cpp(SEXP vMSEXP, SEXP nIterSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP seedSEXP, SEXP adaptEverySEXP, SEXP targetAcceptSEXP, SEXP verboseSEXP, SEXP printEverySEXP, SEXP doMAPSEXP, SEXP zeroIsPaddingSEXP, SEXP alphaMaxOptSEXP, SEXP useMAPinitSEXP, SEXP steps_SEXP, SEXP lb_SEXP, SEXP ub_SEXP, SEXP par0_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter<const NumericMatrix&>::type vM(vMSEXP);
    Rcpp::traits::input_parameter<int>::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter<int>::type burnin(burninSEXP);
    Rcpp::traits::input_parameter<int>::type thin(thinSEXP);
    Rcpp::traits::input_parameter<int>::type seed(seedSEXP);
    Rcpp::traits::input_parameter<int>::type adaptEvery(adaptEverySEXP);
    Rcpp::traits::input_parameter<double>::type targetAccept(targetAcceptSEXP);
    Rcpp::traits::input_parameter<bool>::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter<int>::type printEvery(printEverySEXP);
    Rcpp::traits::input_parameter<bool>::type doMAP(doMAPSEXP);
    Rcpp::traits::input_parameter<bool>::type zeroIsPadding(zeroIsPaddingSEXP);
    Rcpp::traits::input_parameter<double>::type alphaMaxOpt(alphaMaxOptSEXP);
    Rcpp::traits::input_parameter<bool>::type useMAPinit(useMAPinitSEXP);
    Rcpp::traits::input_parameter<Nullable<NumericVector>>::type steps_(steps_SEXP);
    Rcpp::traits::input_parameter<Nullable<NumericVector>>::type lb_(lb_SEXP);
    Rcpp::traits::input_parameter<Nullable<NumericVector>>::type ub_(ub_SEXP);
    Rcpp::traits::input_parameter<Nullable<NumericVector>>::type par0_(par0_SEXP);
    rcpp_result_gen = Rcpp::wrap(bayesian_mcmc_cpp(vM, nIter, burnin, thin, seed, adaptEvery, targetAccept, verbose, printEvery, doMAP, zeroIsPadding, alphaMaxOpt, useMAPinit, steps_, lb_, ub_, par0_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesRegulationInference__bayesian_mcmc_cpp", (DL_FUNC) &_BayesRegulationInference__bayesian_mcmc_cpp, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesRegulationInference(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
